import React, { useEffect, useState } from 'react'
import { NavLink, Navigate, Route, Routes } from 'react-router-dom'
import { api, formatDate } from '../api'
import { Activity, ArrowRight, CheckCircle2, CircleAlert, Database, FileSearch, Gauge, KeyRound, ListChecks, LockKeyhole, RefreshCw, ScrollText, Settings2, ShieldCheck, Users, XCircle } from 'lucide-react'

const adminNav = [
  ['', Gauge, '개요'], ['sources', Database, '데이터 원본'], ['oidc', KeyRound, '인증 및 SSO'], ['migration', RefreshCw, 'Migration Center'], ['security', LockKeyhole, '보안 및 API'], ['audit', ScrollText, '감사 로그'], ['status', Activity, '서비스 상태'],
]

export function Admin({ version }) {
  return <div className="admin-layout"><aside><div><p className="eyebrow">KANVAS CONTROL</p><h2>서비스 관리</h2></div><nav>{adminNav.map(([path, Icon, label]) => <NavLink key={path} to={`/admin/${path}`} end={path === ''}><Icon />{label}</NavLink>)}</nav><footer><ShieldCheck /><span>Administrator zone<small>Kanvas {version?.version}</small></span></footer></aside><main><Routes><Route index element={<AdminOverview />} /><Route path="sources" element={<DataSources />} /><Route path="oidc" element={<OIDCSettings />} /><Route path="migration" element={<MigrationCenter />} /><Route path="security" element={<SecuritySettings />} /><Route path="audit" element={<Audit />} /><Route path="status" element={<ServiceStatus />} /><Route path="*" element={<Navigate to="/admin" replace />} /></Routes></main></div>
}

function AdminHeader({ eyebrow, title, description, action }) { return <header className="admin-header"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{description}</p></div>{action}</header> }

function AdminOverview() {
  const [migration, setMigration] = useState(null); const [status, setStatus] = useState(null)
  useEffect(() => { api('/api/v1/admin/migration').then(setMigration); api('/api/v1/admin/status').then(setStatus) }, [])
  const checks = migration?.checks || []; const pass = checks.filter(c => c.status === 'PASS').length
  return <><AdminHeader eyebrow="SERVICE OVERVIEW" title="Kanvas 운영 현황" description="서비스, 데이터 이전, 보안 상태를 한눈에 확인합니다." /><section className="admin-metrics"><Metric label="서비스" value="정상" note={status?.service?.version || '확인 중'} tone="green" /><Metric label="데이터 모드" value={migration?.sourceMode || '—'} note={`Phase · ${migration?.phase || '—'}`} tone="blue" /><Metric label="전환 준비도" value={`${migration?.readiness || 0}%`} note={`${pass}/${checks.length} checks pass`} tone="amber" /><Metric label="CDC 지연" value={`${migration?.cdcLagMs || 0} ms`} note={`${migration?.failedEvents || 0} failed events`} tone="green" /></section><section className="admin-grid"><article className="admin-card migration-compact"><div className="card-title"><div><h2>Migration Readiness</h2><p>Cutover Gate의 현재 판정</p></div><span className={`state-pill ${migration?.phase === 'CUTOVER_READY' ? 'success' : ''}`}>{migration?.phase || 'LOADING'}</span></div>{checks.length ? checks.slice(0, 8).map(c => <CheckRow key={`${c.category}-${c.name}`} label={`${c.category} · ${c.name}`} status={c.status} />) : <div className="empty">아직 정합성 검사가 실행되지 않았습니다.</div>}<NavLink className="text-link" to="/admin/migration">Migration Center 열기 <ArrowRight /></NavLink></article><article className="admin-card"><div className="card-title"><div><h2>운영 체크리스트</h2><p>오프라인망 서비스 필수 항목</p></div><ListChecks /></div><CheckRow label="PostgreSQL 연결" status={status ? 'PASS' : 'CHECKING'} /><CheckRow label="비밀값 로컬 암호화" status="PASS" /><CheckRow label="Keycloak OIDC 구성" status="ACTION" /><CheckRow label="백업 복구 테스트" status="ACTION" /><CheckRow label="Confluence 원본 Read-only" status="PASS" /></article></section></>
}

function DataSources() {
  const [data, setData] = useState(null); const [dsn, setDsn] = useState(''); const [test, setTest] = useState(null); const [busy, setBusy] = useState(false); const [settings, setSettings] = useState({ attachmentRoot: '/data/confluence/attachments', batchSize: 1000, parallelism: 4 })
  useEffect(() => { api('/api/v1/admin/settings').then(setData) }, [])
  const testPG = async e => { e.preventDefault(); setBusy(true); setTest(null); try { setTest(await api('/api/v1/admin/connections/postgres/test', { method: 'POST', body: JSON.stringify({ dsn }) })) } catch (e) { setTest({ error: e.message }) } finally { setBusy(false) } }
  const save = async e => { e.preventDefault(); for (const [key, value] of Object.entries({ 'migration.attachment_root': settings.attachmentRoot, 'migration.batch_size': Number(settings.batchSize), 'migration.parallelism': Number(settings.parallelism) })) await api('/api/v1/admin/settings', { method: 'PUT', body: JSON.stringify({ key, value, description: 'Migration source setting', secret: false }) }); window.alert('설정을 저장했습니다.') }
  return <><AdminHeader eyebrow="DATA SOURCES" title="데이터 원본" description="부팅 연결 상태를 확인하고 마이그레이션 저장소를 설정합니다." /><section className="connection-grid"><Connection title="Kanvas PostgreSQL" type="TARGET · READ/WRITE" configured={data?.environment?.postgres?.configured} fingerprint={data?.environment?.postgres?.fingerprint} /><Connection title="Confluence MySQL" type="SOURCE · READ ONLY" configured={data?.environment?.confluence?.configured} fingerprint={data?.environment?.confluence?.fingerprint} /></section><section className="admin-card"><div className="card-title"><div><h2>PostgreSQL 연결 테스트</h2><p>입력값은 테스트에만 사용하며 저장하거나 로그로 남기지 않습니다.</p></div><Database /></div><form className="inline-form" onSubmit={testPG}><input type="password" value={dsn} onChange={e => setDsn(e.target.value)} placeholder="postgres://user:password@host:5432/kanvas?sslmode=require" required /><button className="button secondary" disabled={busy}>{busy ? '확인 중…' : '연결 테스트'}</button></form>{test && <div className={test.error ? 'error-box' : 'success-box'}>{test.error || `PostgreSQL ${test.version} · Schema CREATE ${test.schemaCreate ? '허용' : '불가'}`}</div>}</section><form className="admin-card form-grid" onSubmit={save}><div className="card-title full"><div><h2>Migration 원본 설정</h2><p>DSN은 환경변수로 주입하며 나머지 운영값은 여기서 관리합니다.</p></div><Settings2 /></div><label className="span-2">Confluence Attachment Root<input value={settings.attachmentRoot} onChange={e => setSettings({ ...settings, attachmentRoot: e.target.value })} /></label><label>Batch Size<input type="number" min="100" value={settings.batchSize} onChange={e => setSettings({ ...settings, batchSize: e.target.value })} /></label><label>Parallelism<input type="number" min="1" max="32" value={settings.parallelism} onChange={e => setSettings({ ...settings, parallelism: e.target.value })} /></label><button className="button primary">관리 설정 저장</button></form></>
}

function OIDCSettings() {
  const empty = { enabled: false, issuer: '', clientId: '', clientSecret: '', groupsClaim: 'groups', adminGroup: 'kanvas-admins', autoProvision: true }
  const [form, setForm] = useState(empty); const [hasSecret, setHasSecret] = useState(false); const [message, setMessage] = useState('')
  useEffect(() => { api('/api/v1/admin/oidc').then(v => { setForm({ ...empty, ...v.config }); setHasSecret(v.hasClientSecret) }) }, [])
  const save = async e => { e.preventDefault(); setMessage(''); await api('/api/v1/admin/oidc', { method: 'PUT', body: JSON.stringify({ config: form, keepExistingSecret: !form.clientSecret && hasSecret }) }); setHasSecret(hasSecret || !!form.clientSecret); setForm({ ...form, clientSecret: '' }); setMessage('Keycloak OIDC 설정을 저장했습니다.') }
  return <><AdminHeader eyebrow="IDENTITY" title="Keycloak SSO / OIDC" description="Issuer, Client ID, Client Secret만으로 자동 Discovery와 로그인을 구성합니다." /><form className="admin-card form-grid" onSubmit={save}><div className="toggle-row span-2"><div><strong>OIDC 로그인 사용</strong><small>로그인 화면에 Keycloak SSO 버튼을 표시합니다.</small></div><input type="checkbox" checked={form.enabled} onChange={e => setForm({ ...form, enabled: e.target.checked })} /></div><label className="span-2">Issuer URL<input value={form.issuer} onChange={e => setForm({ ...form, issuer: e.target.value })} placeholder="https://keycloak.example/realms/company" required={form.enabled} /></label><label>Client ID<input value={form.clientId} onChange={e => setForm({ ...form, clientId: e.target.value })} placeholder="kanvas" required={form.enabled} /></label><label>Client Secret<input type="password" value={form.clientSecret} onChange={e => setForm({ ...form, clientSecret: e.target.value })} placeholder={hasSecret ? '저장됨 · 변경 시에만 입력' : 'Client secret'} /></label><label>Groups Claim<input value={form.groupsClaim} onChange={e => setForm({ ...form, groupsClaim: e.target.value })} /></label><label>관리자 그룹<input value={form.adminGroup} onChange={e => setForm({ ...form, adminGroup: e.target.value })} /></label><div className="toggle-row span-2"><div><strong>최초 로그인 자동 프로비저닝</strong><small>OIDC subject를 영구 사용자 식별자로 사용합니다.</small></div><input type="checkbox" checked={form.autoProvision} onChange={e => setForm({ ...form, autoProvision: e.target.checked })} /></div>{message && <div className="success-box span-2">{message}</div>}<button className="button primary">OIDC 설정 저장</button></form><section className="admin-card callout"><ShieldCheck /><div><h3>Callback URL</h3><code>https://&lt;kanvas-host&gt;/api/v1/auth/oidc/callback</code><p>Keycloak Client의 Valid redirect URIs에 등록하세요. TLS 종료 프록시는 X-Forwarded-Proto와 X-Forwarded-Host를 전달해야 합니다.</p></div></section></>
}

function MigrationCenter() {
  const [data, setData] = useState(null); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  const load = () => api('/api/v1/admin/migration').then(setData)
  useEffect(load, [])
  const discover = async () => { setBusy(true); setError(''); try { await api('/api/v1/admin/migration/discovery', { method: 'POST' }); await load() } catch (e) { setError(e.message) } finally { setBusy(false) } }
  const transition = async target => { setBusy(true); setError(''); try { await api('/api/v1/admin/migration/transition', { method: 'POST', body: JSON.stringify({ target }) }); await load() } catch (e) { setError(e.message) } finally { setBusy(false) } }
  const d = data?.latestDiscovery
  return <><AdminHeader eyebrow="CONFLUENCE MIGRATION CENTER" title="안전한 온라인 마이그레이션" description="Legacy 원본을 수정하지 않고 Discovery, 검증, Cutover Gate를 제어합니다." action={<button className="button primary" onClick={discover} disabled={busy}><FileSearch /> {busy ? '분석 중…' : 'Schema Discovery'}</button>} />{error && <div className="error-box">{error}</div>}<section className="migration-hero"><div><small>CURRENT PHASE</small><strong>{data?.phase || 'LOADING'}</strong><p>Data Source Mode · {data?.sourceMode || '—'}</p></div><div className="readiness-ring"><strong>{data?.readiness || 0}<small>%</small></strong><span>Readiness</span></div><div><small>CDC LAG</small><strong>{data?.cdcLagMs || 0} ms</strong><p>{data?.failedEvents || 0} failed events</p></div></section><section className="admin-grid"><article className="admin-card"><div className="card-title"><div><h2>Source Discovery</h2><p>실제 설치 스키마 기준</p></div><Database /></div>{d ? <dl className="detail-list"><div><dt>MySQL</dt><dd>{d.databaseVersion}</dd></div><div><dt>Confluence Build</dt><dd>{d.confluenceVersion || 'Unknown'}</dd></div><div><dt>Charset / Collation</dt><dd>{d.characterSet} / {d.collation}</dd></div><div><dt>Tables</dt><dd>{d.tables?.length}</dd></div><div><dt>AO Plugin Tables</dt><dd>{d.aoTables}</dd></div><div><dt>Unknown Tables</dt><dd>{d.unknownTables}</dd></div><div><dt>Discovered</dt><dd>{formatDate(d.createdAt)}</dd></div></dl> : <div className="empty">Schema Discovery를 실행하세요.</div>}</article><article className="admin-card"><div className="card-title"><div><h2>Core Object Counts</h2><p>Confluence 주요 테이블</p></div><FileSearch /></div>{d?.coreCounts ? <div className="count-list">{Object.entries(d.coreCounts).map(([key, value]) => <div key={key}><span>{key}</span><strong>{value.toLocaleString()}</strong></div>)}</div> : <div className="empty">집계 결과가 없습니다.</div>}</article></section><section className="admin-card"><div className="card-title"><div><h2>Cutover Gate</h2><p>필수 검사 전체가 PASS 또는 APPROVED여야 전환됩니다.</p></div><ListChecks /></div><div className="checks-grid">{(data?.checks || []).map(c => <CheckRow key={`${c.category}-${c.name}`} label={`${c.category} · ${c.name}`} status={c.status} />)}{!data?.checks?.length && <div className="empty">검증 엔진 실행 전입니다. Cutover는 허용되지 않습니다.</div>}</div><div className="transition-bar"><span>상태 전환</span>{nextStates(data?.phase).map(target => <button key={target} className="button secondary" disabled={busy} onClick={() => transition(target)}>{target} <ArrowRight /></button>)}</div></section></>
}

function SecuritySettings() { return <><AdminHeader eyebrow="SECURITY & EXTENSIONS" title="보안 및 API" description="Kanvas의 사용자 ACL이 REST와 MCP 요청에도 동일하게 적용됩니다." /><section className="admin-grid"><article className="admin-card callout"><LockKeyhole /><div><h3>개인 키 체계</h3><p>토큰은 SHA-256 해시만 저장하며, 사용자가 개인화 페이지에서 직접 발급·회전·폐기합니다. 평문은 최초 한 번만 노출됩니다.</p><code>Authorization: Bearer knv_...</code></div></article><article className="admin-card callout"><ShieldCheck /><div><h3>MCP Server</h3><p>Streamable HTTP JSON-RPC 엔드포인트와 8개 Wiki 도구를 제공합니다.</p><code>POST /mcp</code></div></article></section><section className="admin-card"><h2>보안 기본값</h2><div className="security-list"><CheckRow label="HttpOnly · SameSite session cookie" status="PASS" /><CheckRow label="CSRF state-changing request guard" status="PASS" /><CheckRow label="CSP · Frame deny · MIME sniffing protection" status="PASS" /><CheckRow label="AES-256-GCM encrypted administrator secrets" status="PASS" /><CheckRow label="Legacy MySQL DML isolation" status="PASS" /></div></section></> }

function Audit() { const [events, setEvents] = useState([]); useEffect(() => { api('/api/v1/admin/audit?limit=200').then(v => setEvents(v || [])) }, []); return <><AdminHeader eyebrow="AUDIT TRAIL" title="감사 로그" description="인증, 관리자 변경, 문서 및 마이그레이션 작업을 애플리케이션 로그와 분리해 기록합니다." /><section className="admin-card audit-table"><div className="table-head"><span>시간</span><span>행위자</span><span>작업</span><span>대상</span></div>{events.map(e => <div key={e.id}><span>{formatDate(e.createdAt)}</span><span>{e.actor}</span><span><b>{e.action}</b></span><span>{e.resourceType} {e.resourceId?.slice(0, 12)}</span></div>)}</section></> }
function ServiceStatus() { const [status, setStatus] = useState(null); useEffect(() => { api('/api/v1/admin/status').then(setStatus) }, []); return <><AdminHeader eyebrow="OBSERVABILITY" title="서비스 상태" description="외부 관측 도구 없이도 핵심 런타임 상태를 확인합니다." /><section className="admin-metrics"><Metric label="HTTP Service" value="UP" note={status?.service?.version} tone="green" /><Metric label="PostgreSQL" value={status?.database?.status || '—'} note={`${status?.database?.totalConnections || 0} connections`} tone="green" /><Metric label="Busy Connections" value={status?.database?.acquiredConnections || 0} note={`${status?.database?.idleConnections || 0} idle`} tone="blue" /></section><section className="admin-card"><h2>Build Information</h2><pre>{JSON.stringify(status?.service, null, 2)}</pre></section></> }

function Metric({ label, value, note, tone }) { return <article className={tone}><small>{label}</small><strong>{value}</strong><span>{note}</span></article> }
function Connection({ title, type, configured, fingerprint }) { return <article className="connection-card"><span className={configured ? 'connected' : 'disconnected'}><Database /></span><div><small>{type}</small><h2>{title}</h2><p>{configured ? `Connected · ${fingerprint}` : 'Not configured'}</p></div><b>{configured ? 'CONNECTED' : 'REQUIRED'}</b></article> }
function CheckRow({ label, status }) { const Icon = status === 'PASS' || status === 'APPROVED' ? CheckCircle2 : status === 'FAIL' ? XCircle : CircleAlert; return <div className={`check-row ${status?.toLowerCase()}`}><Icon /><span>{label}</span><b>{status}</b></div> }
function nextStates(phase) { return ({ LEGACY: ['DISCOVERY'], DISCOVERY: ['SNAPSHOT', 'LEGACY'], SNAPSHOT: ['CDC_SYNC'], CDC_SYNC: ['VERIFY'], VERIFY: ['SHADOW'], SHADOW: ['CUTOVER_READY'], CUTOVER_READY: ['FREEZE', 'LEGACY'], FREEZE: ['FINAL_SYNC', 'WINBACK'], FINAL_SYNC: ['CUTOVER', 'WINBACK'], CUTOVER: ['STABILIZING', 'WINBACK'], STABILIZING: ['COMPLETE', 'WINBACK'], WINBACK: ['LEGACY'], ERROR: ['LEGACY', 'DISCOVERY'] })[phase] || [] }
