import React, { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { api, formatDate } from '../api'
import { RichEditor } from '../components/RichEditor'
import { ChevronRight, Clock3, MessageSquareText, Paperclip, Pencil, Send, Star } from 'lucide-react'

export function PageView() {
  const { pageId } = useParams(); const [page, setPage] = useState(null); const [tab, setTab] = useState('comments'); const [comments, setComments] = useState([]); const [versions, setVersions] = useState([]); const [body, setBody] = useState(''); const [error, setError] = useState('')
  useEffect(() => { api(`/api/v1/pages/${pageId}`).then(setPage).catch(e => setError(e.message)); api(`/api/v1/pages/${pageId}/comments`).then(v => setComments(v || [])).catch(() => {}); api(`/api/v1/pages/${pageId}/versions`).then(v => setVersions(v || [])).catch(() => {}) }, [pageId])
  const addComment = async e => { e.preventDefault(); const c = await api(`/api/v1/pages/${pageId}/comments`, { method: 'POST', body: JSON.stringify({ body }) }); setComments([...comments, c]); setBody('') }
  if (error) return <div className="page-frame"><div className="error-box">{error}</div></div>
  if (!page) return <div className="page-frame muted">문서를 불러오는 중…</div>
  return <article className="page-frame article-page"><div className="breadcrumbs"><Link to="/">홈</Link><ChevronRight /><Link to={`/spaces/${page.spaceId}`}>스페이스</Link><ChevronRight />{page.title}</div><header className="article-header"><div><h1>{page.title}</h1><p>{page.updatedBy} 님이 {formatDate(page.updatedAt)} 수정 · 버전 {page.currentVersion}</p></div><div><button className="icon-button"><Star /></button><Link className="button secondary" to={`/pages/${page.id}/edit`}><Pencil /> 편집</Link></div></header><RichEditor content={page.editorDocument} editable={false} /><footer className="article-meta"><span><Clock3 /> 마지막 수정 {formatDate(page.updatedAt)}</span><span><Paperclip /> 첨부파일 0</span></footer><section className="discussion"><div className="tabs"><button className={tab === 'comments' ? 'active' : ''} onClick={() => setTab('comments')}><MessageSquareText /> 댓글 {comments.length}</button><button className={tab === 'history' ? 'active' : ''} onClick={() => setTab('history')}><Clock3 /> 변경 이력 {versions.length}</button></div>{tab === 'comments' ? <><form className="comment-form" onSubmit={addComment}><textarea value={body} onChange={e => setBody(e.target.value)} placeholder="댓글을 남겨 협업을 이어가세요." required /><button className="button primary"><Send /> 등록</button></form><div className="comments">{comments.map(c => <div key={c.id}><span>{c.createdBy.slice(0, 1)}</span><div><strong>{c.createdBy}<small>{formatDate(c.createdAt)}</small></strong><p>{c.body}</p></div></div>)}{comments.length === 0 && <div className="empty">첫 댓글을 남겨보세요.</div>}</div></> : <div className="history-list">{versions.map(v => <div key={v.id}><span>v{v.version}</span><div><strong>{v.title}</strong><small>{v.createdBy} · {formatDate(v.createdAt)}</small><p>{v.changeMessage || '변경 설명 없음'}</p></div></div>)}</div>}</section></article>
}
